version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: loan-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: loan-app
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
